name: Deploy Java Application to Azure

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Azure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y azure-cli

      - name: Login to Azure
        run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 'latest'

      - name: Login to ACR
        run: echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group helmdemo-resource-group  --name helmdemo-cluster-1

      - name: Deploy to AKS using Helm
        run: |
          helm upgrade --install myapp ./helm/myapp --set image.repository=terafromdemoregistry/helmdemo --set image.tag=latest1

